export const openSystemCategoryTokens = [
  {
    key: "funds-programmes",
    label: "Funds and Programmes",
    token: "--color-open-system-category-funds-programmes",
    alias: "--color-un-green",
    className: "bg-open-system-category-funds-programmes",
    maps: ["Funds and Programmes"],
  },
  {
    key: "research-training",
    label: "Research and Training",
    token: "--color-open-system-category-research-training",
    alias: "--color-un-purple",
    className: "bg-open-system-category-research-training",
    maps: ["Research and Training"],
  },
  {
    key: "secretariat",
    label: "UN Secretariat-administered",
    token: "--color-open-system-category-secretariat",
    alias: "--color-un-blue",
    className: "bg-open-system-category-secretariat",
    maps: ["UN Secretariat"],
  },
  {
    key: "specialized-agencies",
    label: "Specialized Agencies",
    token: "--color-open-system-category-specialized-agencies",
    alias: "--color-un-yellow",
    className: "bg-open-system-category-specialized-agencies",
    maps: ["Specialized Agencies"],
  },
  {
    key: "related-organizations",
    label: "Related Organizations",
    token: "--color-open-system-category-related-organizations",
    alias: "--color-un-orange",
    className: "bg-open-system-category-related-organizations",
    maps: ["Related Organizations"],
  },
  {
    key: "other-entities",
    label: "Other Entities",
    token: "--color-open-system-category-other-entities",
    alias: "--color-un-red",
    className: "bg-open-system-category-other-entities",
    maps: ["Other Entities"],
  },
  {
    key: "neutral",
    label: "Neutral fallback",
    token: "--color-open-system-category-neutral",
    alias: "--color-syschart-gray-dark",
    className: "bg-open-system-category-neutral",
    maps: [
      "International Court of Justice",
      "Intergovernmental and Expert Bodies",
      "Other Bodies",
      "Uncategorized",
      "Unknown values",
    ],
  },
] as const;
